### ISSUE TITLE
可以添加 一个requirements.txt 吗

### ISSUE THREAD

**Issue by mindcont** [zhj12138/pdf-reader#3]
下载下来学习，但是相关的库版本不知道，会报错
`    self.pdfview.setPixmap(QPixmap(pix))
TypeError: QPixmap(): argument 1 has unexpected type 'Pixmap'`

[](https://pymupdf.readthedocs.io/en/latest/znames.html)

**Comment by snowzhaozhj** [comment]
我把venv的库直接传上来了，你可以直接用这个虚拟环境，或者你自己根据版本下载也行

**Comment by mindcont** [comment]
![image](https://user-images.githubusercontent.com/13744152/224238177-e2d22779-6a6e-494f-aa54-075ef35261b7.png)

这个 venv的库不全，pymupdf 的版本不知道多少

**Comment by zhj12138** [comment]
已经添加了requirements.txt了
